[workspace]
members = [
  "crates/sdkwork-api-github-workflow-assembly",
  "crates/sdkwork-api-github-workflow-standalone-gateway",
]
resolver = "2"

[workspace.dependencies]
sdkwork_api_github_workflow_assembly = { path = "crates/sdkwork-api-github-workflow-assembly", package = "sdkwork-api-github-workflow-assembly" }

sdkwork_web_bootstrap = { path = "../sdkwork-web-framework/crates/sdkwork-web-bootstrap", package = "sdkwork-web-bootstrap" }


sdkwork_web_core = { path = "../sdkwork-web-framework/crates/sdkwork-web-core", package = "sdkwork-web-core" }